# 配置端口
server:
  port: 8764
  servlet:
    context-path: /
# 静态文件请求匹配方式
spring:
  mvc:
    static-path-pattern: /**
  #spring.thymeleaf.mode=LEGACYHTML5
  #spring boot 2.x  参数变化
  thymeleaf:
#    suffix: .html
    #前缀，在构建URL时，该前缀被预先设置为视图名称
    prefix: classpath:/templates/
    cache: false
    cache-period: 0
    template:
      cache: false
  devtools:
    livereload:
      enabled: true
  #http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties
  #search multipart
  servlet:
    http:
      multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#logging:
#  level:
#    com.roylao: DEBUG